name = "Mimir"
uuid = "c5446581-5e0b-43af-a4c1-9d0e5e387295"
authors = ["Jordi Bolibar"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Infiltrator = "1.9.7"
JSON = "1.4.0"
Lux = "1.29.4"
Random = "1.11.0"
Revise = "3.13.1"
Statistics = "1.11.1"
